### ISSUE TITLE
Tekton results not working on dogfooding

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/plumbing#1301]
# Expected Behavior

Results works on dogfooding

# Actual Behavior

```
deployment.apps/tekton-results-api                  0/1     0            0           478d
deployment.apps/tekton-results-mysql                0/1     0            0           690d
deployment.apps/tekton-results-watcher              0/1     0            0           478d
```

# Additional Info

We should probably include the update of `dogfooding` in the responsibilities of the release manager, for all projects, or at least creating an issue to track that work.

**Comment by abayer** [comment]
So there are a couple problems here - the most immediate was that the deployments needed to be updated to deal with `PodSecurityPolicy` going away, but the bigger one is that we're still using `tekton-results-mysql`, which still doesn't work after fixing the `securityContext`, and is deprecated in the release we're running (v0.3.0) in favor of postgres anyway. Looks like we'll need to [migrate to postgres](https://github.com/tektoncd/results/blob/071edf9065080733298e9f25ba4e80cb211058f6/tools/postgres-migrate/README.md) as well, and it might make the most sense to wait for the next Results release, which will have the fixes for the `PodSecurityPolicy` removal in as well. 

That said, I'm not sure whether we _can_ migrate since we can't get `tekton-results-mysql` to spin up as non-root in the first place.

**Comment by abayer** [comment]
...it's taking hours, but hey. =)

**Comment by abayer** [comment]
Migration done. So we're ok for now, but still will want to upgrade to 0.5.0 or whatever the next Results release is, the first to have https://github.com/tektoncd/results/commit/60e98514b2163e89a38d011a1026a0634b231999 in it.
