### ISSUE TITLE
Chains is broken on dogfooding

### ISSUE THREAD

**Issue by abayer** [tektoncd/plumbing#1344]
So the Chains team apparently are the ones who installed Chains on the dogfooding cluster, and it hasn't been upgraded in...a while. It's running v0.8.0, and its logs are full of:
```
Failed to watch *v1beta1.TaskRun: failed to list *v1beta1.TaskRun: v1beta1.TaskRunList.Items: []v1beta1.TaskRun: v1beta1.TaskRun.Status: v1beta1.TaskRunStatus.TaskRunStatusFields: TaskRunResults: []v1beta1.TaskRunResult: v1beta1.TaskRunResult.Value: ReadString: expects " or n, but found [, error found in #10 byte of ...|,"value":[]}],"taskS|..., bigger context ...|"failed"},{"name":"files","type":"array","value":[]}],"taskSpec":{"params":[{"description":"Number o|...
```

I don't know if this is something that would be fixed by just upgrading to v0.14.0 (the latest release), and I don't know exactly _how_ it was installed in the first place. But this really should get fixed.

**Comment by lbernick** [comment]
Should be fixed now thanks to @afrittoli upgrading the cluster to chains v0.14-- thank you!

**Comment by wlynch** [comment]
More info as to why this broke -

There was a backwards incompatible client change in the Pipelines API that broke Chain's ability to fetch resource data. Though Chains has logic to retry a certain amount of times before giving up, this didn't apply here since the Chains controller couldn't parse the object to see the retry state, so any Run objects that were affected reconciled forever.

Chains controller [serves a bunch of useful metrics on `/metrics`](https://knative.dev/docs/serving/observability/metrics/serving-metrics/#controller) that would help detect problems like this. I see we have some prometheus jobs running on the cluster - what's the best way to make sure these metrics are collected in dogfooding?

**Comment by lbernick** [comment]
@wlynch what's the Pipelines change you're referring to?

**Comment by wlynch** [comment]
Based on the error message this one looks like it was https://github.com/tektoncd/pipeline/commit/d389ed229bb0b1ed9329dadf2869d1b17751159b#diff-e76276785b79837e5a02d5e687fe27d2bb427c389cbdc348627561a1cb3d2a2fL42

```diff
// TaskRunResult used to describe the results of a task
type TaskRunResult struct {
	// Name the given name
	Name string `json:"name"`
	// Type is the user-specified type of the result. The possible type
	// is currently "string" and will support "array" in following work.
	// +optional
	Type ResultsType `json:"type,omitempty"`

	// Value the given value of the result
-	Value string `json:"value"`
+	Value ArrayOrString `json:"value"`
}
```

Old clients don't know how to handle the new field if it's an array. If it was a string it would be handled okay (this is probably why we never noticed it for awhile).
