### ISSUE TITLE
Flakyness reports and retryer

### ISSUE THREAD

**Issue by chmouel** [tektoncd/plumbing#176]
Prow has some nice tools to reports Flakyness : 

https://github.com/knative/test-infra/tree/master/tools/flaky-test-reporter

and even automatically retry : 

https://github.com/knative/test-infra/tree/master/tools/flaky-test-retryer

It would be a good idea to try installing both, at least at first running the reporter for a bit so we can have some visibilities and see if we can enable retryer on a test repo (I like to propose CLI because we have quite a lot of them there).

**Comment by bobcatfish** [comment]
I'd like to push back on the flakiness retrier: retrying tests that fail hides underlying problems and makes them easier to ignore and harder to fix in the future.

When we have flakey tests I'd rather only retry them in extreme cases, when we're sure we understand why they're failing. Failures can be caused by a) poorly written tests b) actual bugs or c) unavoidable circumstances. c) is the rarest case and also the only case in which I'd want to retry a test.
