### ISSUE TITLE
Standardize yaml/markdown formatters / linters

### ISSUE THREAD

**Issue by wlynch** [tektoncd/plumbing#179]
We should have standardized yaml and markdown linters. In a few issues, there's been problems with different forms of linters conflicting with each other causing issues (e.g. https://github.com/tektoncd/triggers/pull/323 uses prettier, which seems to conflict with what yamllint wants).

Leading candidate is [prettier](https://prettier.io/) due to its popularity (35k+ stars on GitHub), support for both markdown and yaml (among other formats), and support for various editors (vim, emacs, VS Code, etc)

### Open questions
- Is prettier the best option? Are there other tools that would be a better fit? Let us know!

**Comment by dibyom** [comment]
I like `prettier` since it actually formats the code for me!

That being said the issue with tektoncd/triggers#323 is not with `yamllint` -- we have a homegrown [checker](https://github.com/tektoncd/triggers/blob/master/hack/update-docs.sh) that looks for comments like `<!-- *FILE: file-path -->` in markdown files and checks that the codeblock following the comment has the same content as the file referenced in the comment.
(The issue should fixed in https://github.com/tektoncd/triggers/pull/344)

**Comment by dibyom** [comment]
Now that I'm 3 weeks wiser, I'd like to walk back on my `prettier` recommendation a bit: Turns out it actually deleted some codeblocks e.g. https://github.com/tektoncd/triggers/pull/323/files#diff-668b405103de84314198315ff8a750f1L96 :cry:
