### ISSUE TITLE
check-pr-has-kind-label should keep applying until fails or succeeds

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/plumbing#400]
# Expected Behavior

check-pr-has-kind-label is a required check - contributors should be able to depend on it working instead of it getting stuck and blocking their PRs until they intervene

# Actual Behavior

Sometimes the check is forever pending, e.g. on https://github.com/tektoncd/pipeline/pull/2541 this happened and we had to remove and re-add the kind label to trigger it running.

it seems like something interrupts execution (not sure what) and it never tries again.

# Steps to Reproduce the Problem

Not sure! We probably need to approach this from 2 angles:

1. try to figure out what is going wrong and fix it
2. find a way to make this more robust in general so that if things go wrong and interrupt execution of any tekton based checks, PRs are not stuck

**Comment by afrittoli** [comment]
This helps https://github.com/tektoncd/plumbing/pull/390.

When a PR is synced, that status is reset - I'm not sure if it's because the check is marked as required - GitHub does not do that for all check I think.
In any case, running the job on sync ensures that the check does not remain in a limbo state.

I made the PR and then forgot to apply it :( it is applied now and it seems to be working.
