### ISSUE TITLE
Improve reliability of the check-pr-has-kind-label job 

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/plumbing#888]
### Expected Behaviour

The `check-pr-has-kind-label` job should consistently report the correct state of kind labels on any given PR.

### Actual Behaviour

This check can sometimes get confused - it will run on one update but not others, or will check an older "version" of the PR and incorrectly determine that no kind label has been applied.

### More Information

The `check-pr-has-kind-label` job is run when a PR is created or updated to confirm that it is labelled with its "kind" - bug, feature, etc.

Related resources:
- [TriggerTemplate](https://github.com/tektoncd/plumbing/blob/main/tekton/ci/templates/all-template.yaml)
- [Pipeline](https://github.com/tektoncd/plumbing/blob/main/tekton/ci/jobs/tekton-kind-label.yaml)
- [Task](https://github.com/tektoncd/plumbing/blob/main/tekton/ci/jobs/tasks.yaml#L68-L134)

**Comment by afrittoli** [comment]
It looks like something has changed related to `Conditions` and `CloudEvents`.

When requesting the `/test <some-ci-job` for a CI job that is not the label check, the `PipelineRun` for the label check is started, the `Condition` on the name is evaluated and once it fails, the `PipelineRun` completes.
In this process the `TaskRun` should not be not started at all, because the `Condition` needs to be evaluated before, and indeed there is `TaskRun` to be found on the cluster. However the events about the `TaskRun` are sent:

![image](https://user-images.githubusercontent.com/2205608/145036711-684623a3-89cc-42dd-8923-12c993803357.png)

A moment later, events for the `TaskRun` associated to the `Condition` are sent, however the `start` event seems to be missing:

![image](https://user-images.githubusercontent.com/2205608/145037090-bf4c1a76-b4aa-4647-a47c-f6ca740019ac.png)

The event about the `Condition` includes the `conditionName`  and `conditionCheck` labels, which can be used to filter our the event (as it is done today), but events about the label `TaskRun` cause the CI job to be marked as pending on GitHub side - since the `TaskRun` is never executed it stays on pending indefinitely, until a retest of the label check is requested

![image](https://user-images.githubusercontent.com/2205608/145037513-b8d1468a-f507-4b98-9aa6-8f797a2f694f.png)

Looking into the event, the `taskSpec` embedded in the `spec` shows that this event actually comes from the condition:

![image](https://user-images.githubusercontent.com/2205608/145038176-d93f9c51-b910-4afc-b7cc-ae8ae044dd5a.png)

Rewriting this check in the `ci-workspace` folder, without `Conditions` would help, but we may still need to fix the issue on `Conditions`? May be not since they are deprecated?

**Comment by afrittoli** [comment]
https://github.com/tektoncd/plumbing/pull/948
